# Makefile para realizar a compilação
#gentree_test: gentree_test.c ../lib/gentree.c ../lib/gentree.h
#	gcc -o gentree_test gentree_test.c ../lib/gentree.c -I.

btree_test: btree_test.c ../lib/btree.c ../lib/btree.h
	gcc -o btree_test btree_test.c ../lib/btree.c -I.